info:
  contact: {}
paths:
  /api/v1/all-order:
    get:
      consumes:
      - application/json
      description: Obtém todas as ordens com base nos parâmetros de pesquisa
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Obter todas as ordens
      tags:
      - Order
  /api/v1/all-restaurant:
    get:
      consumes:
      - application/json
      description: Encontra todos os restaurantes
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "result"}'
          schema:
            type: string
      summary: Buscar todos restaurante
      tags:
      - Restaurant
  /api/v1/create-order:
    post:
      consumes:
      - application/json
      description: Cria uma nova ordem com base nos parâmetros fornecidos
      parameters:
      - description: Id do restaurante que criou a ordem de pedido pro usuario
        in: query
        name: RestaurantID
        required: true
        type: string
      - description: Comidas/Pedido
        in: query
        name: Items
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Criar uma nova ordem
      tags:
      - Order
  /api/v1/create-restaurant:
    post:
      consumes:
      - application/json
      description: Criação de novos restaurantes
      parameters:
      - description: Nome do Restaurante
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Restaurante criado"}'
          schema:
            type: string
      summary: Criar novo restaurante
      tags:
      - Restaurant
  /api/v1/find-order:
    get:
      consumes:
      - application/json
      description: Obtém uma ordem com base nos parâmetros de pesquisa
      parameters:
      - description: Numero do pedido
        in: query
        name: orderNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Obter uma ordem
      tags:
      - Order
  /api/v1/find-restaurant:
    get:
      consumes:
      - application/json
      description: Encontra um restaurante
      parameters:
      - description: Nome do Restaurante
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Buscar um restaurante
      tags:
      - Restaurant
  /api/v1/food:
    get:
      consumes:
      - application/json
      description: Encontra alimentos com base nos parâmetros de pesquisa
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Alimentos encontrados"}'
          schema:
            type: string
      summary: Encontrar alimentos
      tags:
      - Food
    post:
      consumes:
      - application/json
      description: Criar novos alimentos :)
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      - description: Valor do Produto
        in: query
        name: price
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Registro adicionado com sucesso"}'
          schema:
            type: string
      summary: Criar alimentos
      tags:
      - Food
  /api/v1/status-order:
    put:
      consumes:
      - application/json
      description: Altera o status de uma ordem com base nos parâmetros fornecidos
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Alterar o status de uma ordem
      tags:
      - Order
swagger: "2.0"
