info:
  contact: {}
paths:
  /api/create-user:
    post:
      consumes:
      - application/json
      description: Criar um usuario a partir das novas infos
      parameters:
      - description: Email do usuario
        in: query
        name: Email
        required: true
        type: string
      - description: Nome do usuario
        in: query
        name: Name
        required: true
        type: string
      - description: Endereço do usuario
        in: query
        name: Adress
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Criar um novo usuario
      tags:
      - User
  /api/edit-adress:
    put:
      consumes:
      - application/json
      description: Editar um usuario a partir das novas infos
      parameters:
      - description: Password para editar as novas info
        in: query
        name: Password
        type: string
      - description: Email para editar as novas info
        in: query
        name: Email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Editar usuario (Password)
      tags:
      - User
  /api/edit-email:
    put:
      consumes:
      - application/json
      description: Editar um usuario a partir das novas infos
      parameters:
      - description: Email para editar as novas info
        in: query
        name: Email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Editar usuario (Email)
      tags:
      - User
  /api/edit-name:
    put:
      consumes:
      - application/json
      description: Editar um usuario a partir das novas infos
      parameters:
      - description: Name para editar as novas info
        in: query
        name: Name
        type: string
      - description: Email para editar as novas info
        in: query
        name: Email
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Editar usuario (Name)
      tags:
      - User
  /api/get-user:
    get:
      consumes:
      - application/json
      description: Buscar um usuario dentro da db
      parameters:
      - description: Email para pegar um usuario especifico
        in: query
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Pegar um usuario
      tags:
      - User
  /api/loggout:
    put:
      consumes:
      - application/json
      description: Altera o modo de login para false
      parameters:
      - description: Email para pegar o atributo do login
        in: query
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Desconectar o usuario
      tags:
      - Login
  /api/login:
    put:
      consumes:
      - application/json
      description: Altera o modo de login para true
      parameters:
      - description: Email para pegar o atributo do login
        in: query
        name: Email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Conectar o usuario
      tags:
      - Login
  /api/v1/all-order:
    get:
      consumes:
      - application/json
      description: Obtém todas as ordens com base nos parâmetros de pesquisa
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Obter todas as ordens
      tags:
      - Order
  /api/v1/all-restaurant:
    get:
      consumes:
      - application/json
      description: Encontra todos os restaurantes
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "result"}'
          schema:
            type: string
      summary: Buscar todos restaurante
      tags:
      - Restaurant
  /api/v1/create-order:
    post:
      consumes:
      - application/json
      description: Cria uma nova ordem com base nos parâmetros fornecidos
      parameters:
      - description: Id do restaurante que criou a ordem de pedido pro usuario
        in: query
        name: RestaurantID
        required: true
        type: string
      - description: Comidas/Pedido
        in: query
        name: Items
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Criar uma nova ordem
      tags:
      - Order
  /api/v1/create-restaurant:
    post:
      consumes:
      - application/json
      description: Criação de novos restaurantes
      parameters:
      - description: Nome do Restaurante
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Restaurante criado"}'
          schema:
            type: string
      summary: Criar novo restaurante
      tags:
      - Restaurant
  /api/v1/find-order:
    get:
      consumes:
      - application/json
      description: Obtém uma ordem com base nos parâmetros de pesquisa
      parameters:
      - description: Numero do pedido
        in: query
        name: orderNumber
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Obter uma ordem
      tags:
      - Order
  /api/v1/find-restaurant:
    get:
      consumes:
      - application/json
      description: Encontra um restaurante
      parameters:
      - description: Nome do Restaurante
        in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Buscar um restaurante
      tags:
      - Restaurant
  /api/v1/food:
    get:
      consumes:
      - application/json
      description: Encontra alimentos com base nos parâmetros de pesquisa
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Alimentos encontrados"}'
          schema:
            type: string
      summary: Encontrar alimentos
      tags:
      - Food
    post:
      consumes:
      - application/json
      description: Criar novos alimentos :)
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      - description: Valor do Produto
        in: query
        name: price
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Registro adicionado com sucesso"}'
          schema:
            type: string
      summary: Criar alimentos
      tags:
      - Food
  /api/v1/status-order:
    put:
      consumes:
      - application/json
      description: Altera o status de uma ordem com base nos parâmetros fornecidos
      parameters:
      - description: Nome do alimento
        in: query
        name: name
        required: true
        type: string
      - description: Descrição do alimento
        in: query
        name: description
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"message": "Result"}'
          schema:
            type: string
      summary: Alterar o status de uma ordem
      tags:
      - Order
swagger: "2.0"
